apiVersion: v1
kind: Service

metadata:
  name: ekstest-service
  namespace: practice

spec:
  selector:
    app: ekstest

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer
